-- UNPIVOT 
DECLARE 
  v_cur SYS_REFCURSOR;
  v1 CHAR(2);
  v2 CHAR(6);
  v3 VARCHAR(20);
  v4  NUMBER(10);
BEGIN 
  PKG_DASHBOARD_FISCAL.SP_SEL_SELECIONAR_BATIMENTO1('201912', '202012', '', '', '0', '', '', 'Todas', 'Todos' , 'PIVOTAB','VALOR', 'TMP_DASHFI_14598_10_213117', v_cur); 
  LOOP
    FETCH v_cur INTO v1, v2, v3, v4;
    EXIT WHEN v_cur%NOTFOUND;
    dbms_output.put_line(v1 || ' - ' || v2 || ' - ' || v3 || ' - ' || v4);
  END LOOP;
  CLOSE v_cur;
END;

SELECT L.*, ROWID  FROM T_TOT_DASHBOARD_FISCAL_LAYOUT L;

SELECT * FROM ( 
       SELECT AF.CSP, AF.MES_REFERENCIA, AF.DES_GRUPO_SITUACAO, CAST((SUM(AF.VLR_RESUMO)/1000) AS NUMERIC(15,2)) VALOR
              FROM T_TOT_DASHBOARD_FISCAL AF  
              INNER JOIN SCH_DW_OI.T_GRUPO_SITUACAO GR ON GR.COD_SITUACAO = AF.COD_SITUACAO  
              WHERE AF.TAB_TEMP = 'TMP_DASHFI_14676_17_142730' 
                    AND AF.MES_REFERENCIA IS NOT NULL  
              GROUP BY AF.CSP, AF.MES_REFERENCIA, AF.DES_GRUPO_SITUACAO
              ORDER BY AF.CSP, GR.ORDEM
              ) FATO PIVOT
       (  SUM(NVL(VALOR,0))
          FOR (MES_REFERENCIA) IN ( '201912' as "201912",'202001' as "202001",'202002' as "202002" )
       ) ORDER BY 1

