SELECT COD_REMETENTE, CICLO_NF, SUM(VLR_TOTAL_ARQ) 
       FROM T_CTRL_ARQ_FISCAIS_BRT af 
       WHERE to_char(af.dat_emissaonf,'YYYYMM') BETWEEN '201912' AND '201912' 
             AND AF.STATUS_RECEPCAO <> 5
       GROUP BY COD_REMETENTE, CICLO_NF
       ORDER BY 1,2;
SELECT COD_HOLDING, CICLO, SUM(valor_contabil) 
       FROM solICITACAO_CARGA_PRE_GFX_BRT sol
       INNER JOIN RESUMO_FISCAL_GFX_BRT det ON sol.id_carga=det.id_carga AND SOL.TIPO_DEMONSTRATIVO = 'RESU'
       INNER JOIN T_SIGLA_HOLDING_BRT HC ON SOL.COD_HOLDING = HC.SIGLA_HOLDING
       WHERE MES_REFERENCIA BETWEEN '201912' AND '201912'
       GROUP BY COD_HOLDING, CICLO
       ORDER BY 1,2;
SELECT SUM(VLR_RESUMO) FROM SOLICITACAO_CARGA_PRE_GFX_BRT WHERE MES_REFERENCIA BETWEEN '202001' AND '202001';

SELECT * FROM T_EMAIL_CONTROLEENVIO_BRT E;
SELECT * FROM c14db00.t_recepcao rec WHERE rec.seq_recepcao = 269052;
SELECT * FROM t_ctrl_arq_fiscais_brt af;
SELECT af.*, (SELECT COUNT(1) FROM T_EMAIL_CONTROLEENVIO_BRT em WHERE em.id_seq_recepcao=af.seq_recepcao) FROM t_ctrl_arq_fiscais_brt af WHERE dat_recepcao > '2020-02-01' AND (SELECT COUNT(1) FROM T_EMAIL_CONTROLEENVIO_BRT em WHERE em.id_seq_recepcao=af.seq_recepcao) >0;
SELECT * FROM SOLICITACAO_CARGA_PRE_GFX_BRT;
SELECT * FROM RESUMO_FISCAL_GFX_BRT;
SELECT * FROM t_empresa WHERE cod_eotemp='003';

SELECT * FROM SOLICITACAO_CARGA_PRE_GFX_BRT;
SELECT * FROM TMP_DASHFI_14570_06_094148;
TRUNCATE TABLE TMP_DASHFI_14517_06_090107;
DROP TABLE TMP_DASHFI_14517_06_090107;

SELECT * FROM (
                                SELECT CSP, MES_REFERENCIA, DES_GRUPO_SITUACAO, VALOR FROM (
                                       SELECT CSP, MES_REFERENCIA, SUM(NVL(VLR_TCOF,0)) AS VLR_TCOF, SUM(nvl(VLR_RESUMO,0)) AS VLR_RESUMO, des_grupo_situacao, round(nvl(cast((SUM(case when nvl(VLR_RESUMO,0) > 0 then VLR_RESUMO else nvl(VLR_TCOF,0) end)/1000) AS NUMERIC(15,2)),0),0) Valor                FROM TMP_DASHFI_14570_06_152610
               GROUP BY CSP, MES_REFERENCIA, DES_GRUPO_SITUACAO
        ) FATO)
   PIVOT
   (  SUM(NVL(VALOR,0))
      FOR (MES_REFERENCIA) IN ( '201906' as "201906",'201907' as "201907",'201908' as "201908",'201909' as "201909",'201910' as "201910",'201911' as "201911",'201912' as "201912" )
   )
   ORDER BY 1,2;

