CREATE OR REPLACE PACKAGE PKG_DASHBOARD_FISCAL
AS
   PROCEDURE SP_SEL_FILTROS_HOLDING( P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_FILTROS_UF( P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_LAYOUT( P_USER_ID CHAR, P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_UPD_LAYOUT( 
     P_USER_ID          CHAR,
     P_VLR_SUPERIOR_INI NUMBER,
     P_VLR_SUPERIOR_FIM NUMBER,
     P_ID_SUPERIOR_COR  CHAR,
     P_VLR_META         NUMBER,
     P_ID_META_COR      CHAR,
     P_VLR_INFERIOR_INI NUMBER,
     P_VLR_INFERIOR_FIM NUMBER,
     P_ID_INFERIOR_COR  CHAR);

   PROCEDURE SP_SEL_FILTROS_GRUPO_SITUACAO( P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_ACIONAMENTOS_UF( 
      P_CSP       CHAR,
      P_MESREF    VARCHAR2,
      P_TAB_FATO  VARCHAR2,
      P_FILTROS   OUT SYS_REFCURSOR
      );

   PROCEDURE SP_SEL_GERENCIAL1_DETALHADO( 
      P_CSP       VARCHAR2 := NULL,
      P_MESREF    VARCHAR2 := NULL,
      P_GR_SIT    VARCHAR2 := NULL,
      P_TAB_FATO  VARCHAR2,
      P_FILTROS   OUT SYS_REFCURSOR 
      );

   PROCEDURE SP_SEL_GERENCIAL1_RESUMIDO( 
      P_CSP       CHAR := NULL,
      P_MESREF    CHAR := NULL,
      P_GR_SIT    VARCHAR2 := NULL,
      P_TAB_FATO  VARCHAR2,
      P_FILTROS   OUT SYS_REFCURSOR 
      );

   PROCEDURE SP_SEL_BATIMENTO1_LIMPATAB (
      P_TAB_FATO VARCHAR2
      );

   PROCEDURE SP_SEL_BATIMENTO1_GERATAB (
      P_MESREFINI CHAR,
      P_MESREFFIM CHAR,
      P_OPERADORA CHAR,
      P_UF CHAR,
      P_CSP CHAR,
      P_CICLOINI CHAR,
      P_CICLOFIM CHAR,
      P_SITUACAO CHAR,
      P_STATUS CHAR,
      P_VISAO CHAR := 'PIVOTAB',
      P_CAMPO CHAR := 'VALOR',
      P_TAB_FATO OUT VARCHAR2 );

   PROCEDURE SP_SEL_BATIMENTO1_GERATAB_V7 (
      P_MESREFINI CHAR,
      P_MESREFFIM CHAR,
      P_OPERADORA CHAR,
      P_UF CHAR,
      P_CSP CHAR,
      P_CICLOINI CHAR,
      P_CICLOFIM CHAR,
      P_SITUACAO CHAR,
      P_STATUS CHAR,
      P_VISAO CHAR := 'PIVOTAB',
      P_CAMPO CHAR := 'VALOR',
      P_TAB_FATO OUT VARCHAR2 );

   PROCEDURE SP_SEL_BATIMENTO1_GERATAB_TCOF (
      P_MESREFINI CHAR,
      P_MESREFFIM CHAR,
      P_OPERADORA CHAR,
      P_UF CHAR,
      P_CSP CHAR,
      P_CICLOINI CHAR,
      P_CICLOFIM CHAR,
      P_SITUACAO CHAR,
      P_STATUS CHAR,
      P_VISAO CHAR := 'PIVOTAB',
      P_CAMPO CHAR := 'VALOR',
      P_TAB_FATO OUT VARCHAR2 );

   PROCEDURE SP_SEL_SELECIONAR_BATIMENTO1 (
      P_MESREFINI CHAR,
      P_MESREFFIM CHAR,
      P_OPERADORA CHAR,
      P_UF CHAR,
      P_CSP CHAR,
      P_CICLOINI CHAR,
      P_CICLOFIM CHAR,
      P_SITUACAO CHAR,
      P_STATUS CHAR,
      P_VISAO CHAR := 'PIVOTAB',
      P_CAMPO CHAR := 'VALOR',
      P_TABELA_FATO VARCHAR2,
      P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_SELECIONAR_BATIMENTO3(
      P_TABELA_FATO VARCHAR2,
      P_FILTROS OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_BATIMENTO3_DETATLHADA( 
      P_CSP       VARCHAR2,
      P_MESREFI    VARCHAR2,
      P_MESREFF    VARCHAR2,
      P_GR_SIT    VARCHAR2,
      P_TAB_FATO  VARCHAR2,
      P_FILTROS   OUT SYS_REFCURSOR );

   PROCEDURE SP_SEL_GRAFICO (
      P_TAB_FATO CHAR,
      P_GRAFICO_STR OUT CLOB );

   PROCEDURE SP_SEL_GRAFICOBAIDU (
      P_TAB_FATO CHAR,
      P_GRAFICO_STR OUT CLOB );

   PROCEDURE SP_SEL_GERENCIAL2( 
      P_CSP       CHAR := NULL,
      P_MESREF    CHAR := NULL,
      P_GR_SIT    VARCHAR2 := NULL,
      P_TAB_FATO  VARCHAR2,
      P_FILTROS   OUT SYS_REFCURSOR );

END PKG_DASHBOARD_FISCAL;
/
